# Configuration for Docker environment
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

# Database setup for Docker - connects to postgres service
database:
  host: postgres
  port: 5432
  name: photopooserverpod
  user: postgres

# Redis setup for Docker
redis:
  enabled: true
  host: redis
  port: 6379