name: photopooserverpod_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
<<<<<<< HEAD
  serverpod_client: 2.4.0
  serverpod_auth_client: ^2.0.0
=======
  serverpod_client: ^2.9.1
>>>>>>> 57c8224b224950818b9ce43c8ea947fb7c86eff1
